SECRETE_KEY: "9eoe76)ngvv6znwvfz+2fmv!7lr4vsr-(qvwhu0n2&$%1ia+!)"
DEBUG: "True"


ACCESS_TOKEN_LIFETIME: "5"  #minutes
REFRESH_TOKEN_LIFETIME: "1"  #days
SLIDING_TOKEN_LIFETIME: "5"  #minutes
SLIDING_TOKEN_REFRESH_LIFETIME': "1"  #days


ENGINE: "mysql"
NAME: "db"
USER: "root"
PASSWORD: "1234567890"
HOST: "db"
PORT: "3306"
