version: '3'

services:
  cache:
    image: memcached:alpine
    ports:
      - 11211:11211
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '1234567890'
      MYSQL_ROOT_PASSWORD: '1234567890'
    ports:
     - '3306:3306'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
  